project:
  type: website

website:
  title: "Data4Humanity"
  site-url: "https://ieshreya.github.io/Data4Humanity/"
  navbar:
    right:
      - about.qmd
      # - icon: github
        # href: https://github.com/
      - icon: twitter-x
        href: https://x.com/eyeshreya
      - icon: rss-fill
        href: index.xml
format:
  html:
    theme:
      - simplex  
      # - litera
      # - brand
      - custom.scss
    # fontsize: small
    css: styles.css



